### ISSUE TITLE
Instructions may have a slight typo

### ISSUE THREAD

**Issue by MasterJubei** [pioto1225/evdi#3]
Hey, thanks a lot for making this. It works great in my very limited testing on a ryzen 5700u laptop.
In the instructions you mention:

```
5. append "vmap_texture=1" to /etc/modprobe/evdi.conf (the content of the file should look like this "options evdi initial_device_count=4 vmap_texture=1")
6. reboot.

```
I believe that should be /etc/modprobe.d 
not /etc/modprobe

At least on Ubuntu 21.10, but I assume it is like that for the other versions of Ubuntu.

**Comment by pioto1225** [comment]
Yes, it is the case for Debian as well. I made the update. Thanks!
