### ISSUE TITLE
Is it ok to install with evdi 1.10.1?

### ISSUE THREAD

**Issue by NikhilSaini38** [pioto1225/evdi#4]
Update for stable evdi AUR is showing an update for 1.10.1 today. is it ok to patch it with this driver? or should i wait?

**Comment by pioto1225** [comment]
I merged the latest DisplayLink 1.10.1 driver into amd_vmap_texture branch.

**Comment by NikhilSaini38** [comment]
Thank you

**Comment by NikhilSaini38** [comment]
Is it okay to apply this patch to evdi 1.10,1-2 (update from 1.10.1-1 recieved in AUR)

**Comment by pioto1225** [comment]
amd_vmap_texture branch is tracking DisplayLink's upstream repo (https://github.com/DisplayLink/evdi) and it is up-to-date.
I am not familiar with AUR (Arch?) packaging.
